### ISSUE TITLE
Signup and Signin Page

### ISSUE THREAD

**Issue by Ashutosh-777** [Ashutosh-777/Utility-Watch#1]
[Figma Design](https://www.figma.com/file/UqTGTSjsreqiKDIGF4JUN5/Utility-Tracker?type=design&node-id=0%3A1&mode=design&t=IzUkVHqORvWM9wan-1)
Make sure Code perfectly aligns with the design

**Comment by sampath-kumaramd** [comment]
hey, @Ashutosh-777  can you assign this to me,  I wanna work on this.

**Comment by Ashutosh-777** [comment]
@sampath-kumaramd assigned to you

**Comment by Ashutosh-777** [comment]
> @sampath-kumaramd assigned to you



> hey, @Ashutosh-777 can you assign this to me, I wanna work on this.

@sampath-kumaramd status?

**Comment by hitesh-mori** [comment]
hey,@Ashutosh-777 can you assign this to me ?

**Comment by Ashutosh-777** [comment]
> hey,@Ashutosh-777 can you assign this to me ?

@Hitesh123mori you have been assigned

**Comment by ChanukaUOJ** [comment]
Hello Ashutosh-777

I have completed several flutter apps and some of them are published in the google Play Store also. You can visit my profile and get some idea about my work. If you're interested, You can assign me to this work that I'm very much interested in :) Thank you! Have a nice day!

**Comment by Ashutosh-777** [comment]
> Hello Ashutosh-777
> 
> I have completed several flutter apps and some of them are published in the google Play Store also. You can visit my profile and get some idea about my work. If you're interested, You can assign me to this work that I'm very much interested in :) Thank you! Have a nice day!

You can work on #4 for now

**Comment by Ashutosh-777** [comment]
> > hey,@Ashutosh-777 can you assign this to me ?
> 
> @Hitesh123mori you have been assigned

@Hitesh123mori complete this ISSUE by tomorrow EOD

**Comment by vijaymehrotra** [comment]
Hello @Ashutosh-777 , 
I want to work on this,
please assign this issue to me..

**Comment by hitesh-mori** [comment]
Hello , @Ashutosh-777 
I have sent you a pull request

**Comment by Ashutosh-777** [comment]
> Hello , @Ashutosh-777 I have sent you a pull request

Reviewed!, I have suggested some changes 
Please go through those suggestions

**Comment by Palak4620** [comment]
hello, I want to contribute in this issue, kindly assign this to me

**Comment by Ashutosh-777** [comment]
> hello, I want to contribute in this issue, kindly assign this to me

@Palak4620  you have been assigned

**Comment by Ashutosh-777** [comment]
> Hello @Ashutosh-777 , I want to work on this, please assign this issue to me..

@vijaymehrotra assigned to you

**Comment by vijaymehrotra** [comment]
> > Hello @Ashutosh-777 , I want to work on this, please assign this issue to me..
> 
> @vijaymehrotra assigned to you

hey @Ashutosh-777,
should I use firebase to authenticate user's data...
or do I just have to make the design (no backend!).

**Comment by Ashutosh-777** [comment]
> > > Hello @Ashutosh-777 , I want to work on this, please assign this issue to me..
> > 
> > 
> > @vijaymehrotra assigned to you
> 
> hey @Ashutosh-777, should I use firebase to authenticate user's data... or do I just have to make the design (no backend!).

For now we need just the design part I will posting another issue tmrw for authentication part

**Comment by vijaymehrotra** [comment]
Hello @Ashutosh-777,
I have Updated the Pull Request and updated the code more similar to the Figma design.
Please review my code ...
