### ISSUE TITLE
Objective Page input Page

### ISSUE THREAD

**Issue by Ashutosh-777** [Ashutosh-777/Utility-Watch#15]
Objective Page is already made [Click here to view objective page design,](https://www.figma.com/file/hlgLS9pMctXH2ncCgsMtej/Untitled?type=design&node-id=0%3A1&mode=design&t=PfFD5yZOcYEnVyu8-1) we need another page to take input form the user
[Figma Design](https://www.figma.com/file/fBQJLpGfKxGhUGZaFBEPsr/Untitled?type=design&node-id=0%3A1&mode=design&t=kplzwEcuf88XnzDs-1) for the same is attached here

**Comment by vijaymehrotra** [comment]
Should I override the objective page? 
or should I make a new page (and where do you want this new page).

**Comment by Ashutosh-777** [comment]
> Should I override the objective page? or should I make a new page (and where do you want this new page).

Make new Page
There will be two state for all the widgets one where user has not entered data and second state when user has already filled details
you can use a popup to take input from user (Also record date as well when taking input)

**Comment by Ashutosh-777** [comment]
> > Should I override the objective page? or should I make a new page (and where do you want this new page).
> 
> Make new Page There will be two state for all the widgets one where user has not entered data and second state when user has already filled details you can use a popup to take input from user (Also record date as well when taking input)

or give option to select date

**Comment by Ashutosh-777** [comment]
> Should I override the objective page? or should I make a new page (and where do you want this new page).

@vijaymehrotra assigned to you
