### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Ashutosh-777** [Ashutosh-777/Utility-Watch#16]
Enable Authentication in the App

**Comment by Aryashakya** [comment]
Hi, I would like to work on this.

**Comment by Ashutosh-777** [comment]
@Aryashakya assigned to you

**Comment by Ashutosh-777** [comment]
> @Aryashakya assigned to you

what's the status?

**Comment by Aryashakya** [comment]
> > @Aryashakya assigned to you
> 
> 
> 
> what's the status?

Working on it.

**Comment by Aryashakya** [comment]
#17 Please review it.

**Comment by DarpanNeve** [comment]
do you need firebase auth in the app or custom auth

**Comment by Aryashakya** [comment]
I have used Firebase Authentication.

**Comment by DarpanNeve** [comment]
but firebase_options.dart is not there

**Comment by DarpanNeve** [comment]
ok
