### ISSUE TITLE
Reading Page

### ISSUE THREAD

**Issue by Ashutosh-777** [Ashutosh-777/Utility-Watch#2]
[Figma Design](https://www.figma.com/file/8rY6W06hUmQh5BgwlYpXic/Untitled?type=design&node-id=0%3A1&mode=design&t=DBqH8uzvT3d5k7Cs-1)
Make Sure Code perfectly aligns with the design

**Comment by venkylm10** [comment]
@Ashutosh-777 please assign this issue to me. I wanna work on this.

**Comment by Ashutosh-777** [comment]
> @Ashutosh-777 please assign this issue to me. I wanna work on this.

@venkylm10 assigned to you
