### ISSUE TITLE
Daily Readings

### ISSUE THREAD

**Issue by Ashutosh-777** [Ashutosh-777/Utility-Watch#3]
[Figma Design](https://www.figma.com/file/8yVOaVqQLNdDeBZyEkbxZS/Untitled?type=design&node-id=0%3A1&mode=design&t=B3QAU4R9xA6h7bWp-1)

To implement this design, you may use already available Dart Packages.

**Comment by venkylm10** [comment]
@Ashutosh-777 I wanna work on this, please assign this issue to me

**Comment by Ashutosh-777** [comment]
> @Ashutosh-777 I wanna work on this, please assign this issue to me

@venkylm10 assigned to you
