### ISSUE TITLE
Account Page

### ISSUE THREAD

**Issue by Ashutosh-777** [Ashutosh-777/Utility-Watch#4]
[Figma Design](https://www.figma.com/file/dmRIGH9PG9P0pY4K4odi2y/Untitled?type=design&node-id=0%3A1&mode=design&t=LfBHnCzNnOFgMlfd-1)
Please make sure the code aligns accurately with the design.

**Comment by venkylm10** [comment]
@Ashutosh-777 Can you assign this to me, i would like to work on this

**Comment by vijaymehrotra** [comment]
Hello can I work on this..

**Comment by Ashutosh-777** [comment]
> Hello can I work on this..

assigned to you @vijaymehrotra

**Comment by Palak4620** [comment]
hello, I want to contribute in this issue, kindly assign this to me.

**Comment by Ashutosh-777** [comment]
> hello, I want to contribute in this issue, kindly assign this to me.

assigned to you @Palak4620

**Comment by Ashutosh-777** [comment]
> Hello can I work on this..

what's the status @vijaymehrotra

**Comment by Ashutosh-777** [comment]
> > Hello can I work on this..
> 
> assigned to you @vijaymehrotra

@vijaymehrotra still working on it?

**Comment by Ashutosh-777** [comment]
> > hello, I want to contribute in this issue, kindly assign this to me.
> 
> assigned to you @Palak4620

it shouldn't take much time by when will you be able to complete this issue

**Comment by vijaymehrotra** [comment]
> > > Hello can I work on this..
> > 
> > 
> > assigned to you @vijaymehrotra
> 
> @vijaymehrotra still working on it?

Yes still working on it..
Will be done by tonight..

**Comment by Ashutosh-777** [comment]
> > > > Hello can I work on this..
> > > 
> > > 
> > > assigned to you @vijaymehrotra
> > 
> > 
> > @vijaymehrotra still working on it?
> 
> Yes still working on it.. Will be done by tonight..

alright

**Comment by vijaymehrotra** [comment]
Hello @Ashutosh-777 ,
I have made the Account Page ,
You can review my work , and tell if anything more needed.
