### ISSUE TITLE
Insights Page

### ISSUE THREAD

**Issue by Ashutosh-777** [Ashutosh-777/Utility-Watch#7]
To build this Page we will be using [fl_chart dependency](https://pub.dev/packages/fl_chart). please go through this once to get a better understanding
[Fl_Chart](https://app.flchart.dev/#/bar) {You can visit this site to get an idea of the UI)
We will be showing two graphs on the page 
1.
![image](https://github.com/Ashutosh-777/Utility-Watch/assets/112700624/33f84d87-a05b-408a-9b40-05bb00d39744)
2. 
![image](https://github.com/Ashutosh-777/Utility-Watch/assets/112700624/d18ef016-b83f-454b-9854-93d52e899b7e)

Requirements to be met for this Page
[Figma Design](https://www.figma.com/file/GmkdoupBbTCtMiwrjNHZji/Untitled?type=design&node-id=0%3A1&mode=design&t=8Vqle0WwTGcdKFVx-1)
Necessary comments have been made in the design to help you understand the design of the page make sure to comment if you have any doubt regarding design
**Make your own dummy data to use in graph for Electricity Consumption data should be in KWH and for Water consumption data should be in L **

**Comment by Ashutosh-777** [comment]
We donot expect perfection in this page we just expect for you to implement these two graphs in the Page. Main focus should be implementing these graphs in the app.

**Comment by vivekreddy049** [comment]
I would like to work on this

**Comment by DahVik** [comment]
I would like to work on this one.

**Comment by Ashutosh-777** [comment]
> I would like to work on this

@vivekreddy049 assigned to you

**Comment by vijaymehrotra** [comment]
Hey @Ashutosh-777,
Can I also work on this...

**Comment by DahVik** [comment]
Hey @Ashutosh-777 can I work on this one

**Comment by Ashutosh-777** [comment]
> Hey @Ashutosh-777 can I work on this one

@DahVik assigned to you
