### ISSUE TITLE
Objective Page

### ISSUE THREAD

**Issue by Ashutosh-777** [Ashutosh-777/Utility-Watch#8]
[Figma Design](https://www.figma.com/file/hlgLS9pMctXH2ncCgsMtej/Untitled?type=design&node-id=0%3A1&mode=design&t=PfFD5yZOcYEnVyu8-1)
Attached is the figma design for Objective page

**Comment by vijaymehrotra** [comment]
Hello @Ashutosh-777 ,
I would like to solve this..

**Comment by Ashutosh-777** [comment]
> Hello @Ashutosh-777 , I would like to solve this..

assigned to you @vijaymehrotra 
also reply by when you will be able to complete this?

**Comment by vijaymehrotra** [comment]
> > Hello @Ashutosh-777 , I would like to solve this..
> 
> assigned to you @vijaymehrotra also reply by when you will be able to complete this?
i will be able to do it tomorrow..
